name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}  # :contentReference[oaicite:7]{index=7}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2      # :contentReference[oaicite:8]{index=8}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Deploy/Update CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ secrets.STACK_NAME }}
          template: infra/stack.yml
          parameter-overrides: ImageTag=${{ github.sha }}  # :contentReference[oaicite:9]{index=9}
          no-fail-on-empty-changeset: true
